language: java
jdk: oraclejdk8
env:
  global:
  - secure: e1QxUYcmhZzVNREog+repZ285vg1B9BI3INKA5ylaUcuSmsxIFutZ9a5ktiLzI6M/y0i+YLjjk4JMAtiK3UboPFNSp9R1J3GQAK76/RLqe4sBrgBVOt4NKoebXoniDTF3zqyjsXawOZKabGGxJb7HVlHdgn9mpsWn2MHzyw3Zuw=
  - secure: UX+gs3ZAl12Y/R/KIZ6QCYux+Az895WsCW+99g5uZHgLJPVi2pa0hidLg51wKzQ0QZJH2mvcnUxVzHbTksdZRW97ODxJ4wc2KSUsPGcMEVAHDpKq1bizoC0NUhEOUxjeukX83dRQkloQdVplg8fjqbdXUwLX8i91enVc1m4FT8E=
  - secure: VAl25ftbps2tc0CLVrcm/jSvvw00e0nuEBYzUQISKNziIODUW7PAJaHxBprHKPRBAkQ8qpt6Sm+mX4CuxERMQYkRy3KmPchTY3aehjnQhPXkAUJzkI8UoRYN0wbvvOg1pMwFkCs3V534EPNoOx3OumwFIKzDqpVL+jZG31cs9S4=
  - secure: rV1FDKDwtmRkEBE8vA7bJ9dfQVJp6BP+rK80Z6qmHuu/ht1gXjm+l0hS+aFUWoplP+2GkOxjayU/dOF/q53hxSowP8QzDdBd7TRlT+bU9NKD8zmCkxnYP48rOu74p08C5UUSFm2siMA52lKG1bCxvb018T+yMlqJFwE9Epy8Dgo=
before_install:
- openssl aes-256-cbc -K $encrypted_5a993c55c532_key -iv $encrypted_5a993c55c532_iv
  -in codesigning/codesigning.asc.enc -out codesigning/codesigning.asc
  -d
install: mvn install -DskipTests=true -B
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
- gpg --fast-import codesigning/codesigning.asc
script:
 - mvn test -P !build-extras -B
 - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
      mvn deploy -DskipTests=true -P sign,build-extras --settings codesigning/mvnsettings.xml;
   fi
